; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200

lib_deps = 
    homespan/HomeSpan@1.7.1
    h2zero/NimBLE-Arduino@1.4.3

build_flags = 
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
    -DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=0
    -DCONFIG_BTDM_CTRL_MODE_BTDM=0
    -DCONFIG_BTDM_MODEM_SLEEP=0
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_SLEEP_DISABLED=1
    -DCONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL=1